### PR TITLE
Add support dataset with multiple extensions

### PR DESCRIPTION
**Pull request by TylorShine**
and,
- Added and move from constant vars some arguments to some script for convenient
- Added the list of extensions for specify using dataset to configs, as "extensions"
- Allowed directory names to be separated by a underscores "_" or hyphens "-" when specifying speaker IDs.

Regards.

### CODE REVIEW

**Comment by yxlllc** [comment]
I noticed that you added options about the audio format in preprocess.py, but also in the yaml configuration file, is this a duplicate.? When actually preprocessing, is it now working according to the command line parameters or according to the configuration file ?

**Comment by yxlllc** [comment]
Another problem is that if the names are the same but the format is different, for example, 'abc.wav' and 'abc.flac' coexist, then the preprocessing will generate 'abc.npy' with the same name, and there will be conflicts. ..... I feel that if we want to fully support multiple formats, there will be a lot of code to be changed, and a lot of testing is required

**Comment by TylorShine** [comment]
Thanks for your review and reply!

> When actually preprocessing, is it now working according to the command line parameters or according to the configuration file ?

now, It according to the config file ones.
Since the same configuration file is used when preprocess and training, I thought it had better write the settings in these configuration files.

> I noticed that you added options about the audio format in preprocess.py, but also in the yaml configuration file, is this a duplicate.?  

That's right, I forgot that I added options for testing. I'll remove options (arguments).
  
  
> Another problem is that if the names are the same but the format is different, for example, 'abc.wav' and 'abc.flac' coexist, then the preprocessing will generate 'abc.npy' with the same name, and there will be conflicts.

I see, I'll thinking some better way and trying implement. (easy way is 'abc.npy' to 'abc.wav.npy', or 'abc.flac.npy' ... for now I thought.)

**Comment by TylorShine** [comment]
pushed. I tested draw, preprocess, train_diff, train and main_diff. It seems to be no errors/problems.

Could you please review the code?

**Comment by TylorShine** [comment]
P.S.:
Using about 200 files, 2 speakers with .wav, .flac, .mp3 and .opus formats when tested.
configs:
```yaml
data:
  f0_extractor: 'parselmouth' # 'parselmouth', 'dio', 'harvest', or 'crepe'
  ...
  valid_path: ../ddsp-svc-data/testrun-mini/val # Create a folder named "audio" under this path and put the audio clip in it
  extensions: # List of extension included in the data collection
    - wav
    - flac
    - opus
    - mp3
model:
  type: 'Diffusion'
  ...
```

**Pull request merged**
