### PR TITLE
Update gui_locale.py

### PR DESCRIPTION
**Pull request by Katsuyuki-Karasawa**
add ja_JP

### CODE REVIEW

**Comment by yxlllc** [comment]
Thanks for the translation, but why some English words appear...

**Comment by Katsuyuki-Karasawa** [comment]
I forgot lol.
I'll fix it later.

**Comment by Katsuyuki-Karasawa** [comment]
fix

**Comment by yxlllc** [comment]
You forgot to add Japanese to the language list, see my update

**Comment by Katsuyuki-Karasawa** [comment]
ah sorry
Thank you for adding me to the lang list

**Pull request merged**
